function random_number() {
    num = Math.floor(Math.random() * 6) + 1;
    return num;
}

function sum(dice1 , dice2)
{
    /*generate sum of 2 numbers .
    args: dice1 = random no. generated by random function for dice1.
          dice2 = random no. generated by random function for dice1.

    return: sum of 2 given numbers.*/
    return dice1+dice2

}

function main()
{
    console.log("Welcome to DiceMaster Dice Game!");
    console.log("Press the 'Roll' button to roll the dice:");

        dice1 = random_number();
        dice2 = random_number();
        result = sum(dice1 , dice2);
    console.log("\nThank you for rolling the dice.");
    console.log(`You rolled a ${dice1} and a ${dice2}. The sum is ${result}.`);
    
}
main();
